name: Python package

on:
  push:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Use pkg_tsl2b 
        run: |
          python3 -m venv env; \
          source env/bin/activate; \
          pip install -r requirements.txt; \
          python -c "from pkg_dpy8wq import clean_text; print(clean_text('This is text to clean.'))"; \
          python -c "import pkg_dpy8wq as pkg; print(pkg.clean_text('This is text to clean.'))"; \
          deactivate
